name: API Automated Tests (Newman)

on:
  workflow_dispatch: # Permet le déclenchement manuel (via PowerShell ou l'interface)
  schedule:
    - cron: '0 6 * * 1-5'
    - cron: '0 8 * * 1-5'
    - cron: '0 10 * * 1-5'
    - cron: '0 12 * * 1-5'
    - cron: '0 14 * * 1-5'
    - cron: '0 18 * * 1-5'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  api-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installation de Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Installation des dépendances
      run: npm install

    - name: Exécution de la suite de tests globale
      run: npm run test-all

    # SAUVEGARDE DU RAPPORT DANS LES ARTIFACTS
    - name: Sauvegarde du rapport HTML Global
      if: always() # S'exécute MEME si un test échoue, indispensable pour le debug !
      uses: actions/upload-artifact@v4
      with:
        name: newman-global-html-report
        path: reports/global-report.html
        retention-days: 5 # Le rapport reste téléchargeable pendant 5 jours